config/routes.rb
DemoApp::Application.routes.draw do
  get "sessions/new"

  resources :points
  resources :questions
  resources :users do
    resources :comments
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "users/new"

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"

  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new' 
  match '/signout', :to => 'sessions#destroy'
  match '/dashboard', :to=>'dashboard#index'
  match '/charts', :to=>'charts#index'
  
  match 'points/create', :to=> 'points#create'
  
  root :to => 'users#new'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :points
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  
  def correct
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question, :html => { :class => 'well' }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer1 %>
    <%= f.text_field :answer1 %>
  </div>
  <div class="field">
    <%= f.label :answer2 %>
    <%= f.text_field :answer2 %>
  </div>
  <div class="field">
    <%= f.label :answer3 %>
    <%= f.text_field :answer3 %>
  </div>
  <div class="field">
    <%= f.label :answer4 %>
    <%= f.text_field :answer4 %>
  </div>
 <div class="field">
	<%= f.label :CorrectAnswer %>
	<%= radio_button("question", :correct_answer, 1, :class => 'first-radio') %>
	<%= label_tag(:correct_answer, "1", :class => 'radio-label') %>
	<%= radio_button("question", :correct_answer, 2) %>
	<%= label_tag(:correct_answer, "2", :class => 'radio-label') %>
	<%= radio_button("question", :correct_answer, 3) %>
	<%= label_tag(:correct_answer, "3", :class => 'radio-label') %>
	<%= radio_button("question", :correct_answer, 4) %>
	<%= label_tag(:correct_answer, "4", :class => 'radio-label') %>
  </div>
  <div class="actions">
    <%= f.submit "Create Question", :class => 'btn-primary' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% if current_user.user_type == 0 %>
	
	<h1>Take the Quiz</h1>
	
	<p>This quiz is designed to test your knowledge of <strong>Invega Products</strong>. You will only have once chance to guess the correct answer before moving onto the next one. You cannot skip a question.</p>
	
	<% @questions.each do |question| %>
			<div class="well" id="question_<%=question.id %>">
				<div class="alert alert-danger" style="display:none;">Please select a checkbox</div>
				<div id="question_status_<%= question.id %>"></div>
				<h2><%= question.question %></h2>
				 <form accept-charset="UTF-8" action="/points/create" method="post" data-remote="true" id="form_<%= question.id %>"> 
					<div class="field">
						<%= radio_button("point", :user_answer, 1) %>
						<%= label_tag(:correct_answer, question.answer1 ) %>
						<%= radio_button("point", :user_answer, 2) %>
						<%= label_tag(:correct_answer, question.answer2) %>
						<%= radio_button("point", :user_answer, 3) %>
						<%= label_tag(:correct_answer, question.answer3) %>
						<%= radio_button("point", :user_answer, 4) %>
						<%= label_tag(:correct_answer, question.answer4) %>
					  </div>
					<div class="actions">
						<input type="hidden" id="point_question_correct_answer" name="point[correct_answer]" value="<%= question.correct_answer %>" />
						<input type="hidden" id="point_question_id" name="point[question_id]" value="<%= question.id %>" />
						<input type="hidden" id="point_current_user" name="point[user_id]" value="<%= current_user.id %>" />
						<input type="hidden" id="point_correct" name="point[correct]" value="">
					   <%= submit_tag "Submit", :class => 'btn btn-primary question-submission' %> 
					</div>
				</form>
			</div>
	<% end %>
		<div class="well">
			<h3>Thanks for answering all of the questions! <%= link_to 'Show my Score', points_path %>.</h3>
		</div>
	
<% else %>

	<h1>Sales Quiz</h1>
	<table class="table table-condensed">
	  <tr>
	    <th>Question</th>
	    <th>Answer1</th>
	    <th>Answer2</th>
	    <th>Answer3</th>
	    <th>Answer4</th>
	    <th>Correct Answer</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @questions.each do |question| %>
	  <tr>
	    <td><%= question.question %></td>
	    <td><%= question.answer1 %></td>
	    <td><%= question.answer2 %></td>
	    <td><%= question.answer3 %></td>
	    <td><%= question.answer4 %></td>
		<td><%= question.correct_answer %></td>
	    <td><%= link_to 'Show', question, :class => 'btn btn-primary' %></td>
	    <td><%= link_to 'Edit', edit_question_path(question), :class => 'btn btn-warning' %></td>
	    <td><%= link_to 'Destroy', question, :class => 'btn btn-danger', confirm: 'Are you sure?', method: :delete %></td>
	  </tr>
	<% end %>
	</table>
	
<% end %>

<% if current_user.user_type == 1 %>
	<%= link_to 'New Question', new_question_path %>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @question.question %>
</p>

<p>
  <b>Answer1:</b>
  <%= @question.answer1 %>
</p>

<p>
  <b>Answer2:</b>
  <%= @question.answer2 %>
</p>

<p>
  <b>Answer3:</b>
  <%= @question.answer3 %>
</p>

<p>
  <b>Answer4:</b>
  <%= @question.answer4 %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>