config/routes.rb
DemoApp::Application.routes.draw do
  get "sessions/new"

  resources :points
  resources :questions
  resources :users do
    resources :comments
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "users/new"

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"

  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new' 
  match '/signout', :to => 'sessions#destroy'
  match '/dashboard', :to=>'dashboard#index'
  match '/charts', :to=>'charts#index'
  
  match 'points/create', :to=> 'points#create'
  
  root :to => 'users#new'

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # GET /points
  # GET /points.json
  def index
    @points = Point.all
    @user_points = Point.where('user_id' => current_user)
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(params[:point])
    
    respond_to do |format|
      if @point.save
        logger.debug "Data has been saved"
        flash.now[:success] = "Data has been saved"
        if @point.user_answer == @point.correct_answer
          logger.debug "Correct!"
        end
        
        redirect_to :controller => 'questions', :action => 'index'
      else
      end
    end
  end   
    #render :nothing => true
  
     
    
    #@point.save

    #respond_to do |format|
     # if @point.save
      #  format.html { redirect_to @point, notice: 'Point was successfully created.' }
       # format.json { render json: @point, status: :created, location: @point }
    #  else
     #   format.html { render action: "new" }
      #  format.json { render json: @point.errors, status: :unprocessable_entity }
    #  end
    # end

  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/points_helper.rb
module PointsHelper
  
  def users_answer(question_id)
    user_answer = Question.find(question_id)
  end
  
  def correct_answer(id)
    correct_answer = Question.find(id)
  end
  
end

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :correct_answer %><br />
    <%= f.number_field :correct_answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Your Score</h1>

<p>Below is how you performed on each question</p>

<% @user_points.each do |user_point| %>
	<div class="<% if user_point.correct_answer == user_point.user_answer %>alert-success alert<% else %>alert alert-danger<% end %>">
		<h2><% if (!user_point.question.nil?) %> <%= user_point.question.question %><% end %></h2>
		<% if user_point.correct_answer == user_point.user_answer %>
			<p>Your answer is correct</p>
		<% else %>
			<p>Your answer is correct</p>
		<% end %>
	</div>
<% end %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @point.user_id %>
</p>

<p>
  <b>Question:</b>
  <%= @point.question_id %>
</p>

<p>
  <b>Correct answer:</b>
  <%= @point.correct_answer %>
</p>


<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>