config/routes.rb
DemoApp::Application.routes.draw do
  get "sessions/new"

  resources :points
  resources :questions
  resources :users do
    resources :comments
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "users/new"

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"

  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new' 
  match '/signout', :to => 'sessions#destroy'
  match '/dashboard', :to=>'dashboard#index'
  match '/charts', :to=>'charts#index'
  
  match 'points/create', :to=> 'points#create'
  
  root :to => 'users#new'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div>
		<div class="container">
			<ul class="nav">
				<li class="">
					<% if signed_in? %>
						<%= link_to 'Dashboard', dashboard_path %>
					<% else %>
						<%= link_to 'Sign Up', new_user_path %>
					<% end %>
				</li>
					<% if signed_in? %> 
						<% if current_user.user_type == 0 %>
							<li class=""><%= link_to 'Take the Quiz', questions_path %></li>
							<li class=""><%= link_to 'My Score', points_path %></li>
						<% else %>
							<li class=""><%= link_to 'Create a Quiz', new_question_path %></li>
							<li class=""><%= link_to 'My Questions', questions_path %></li>
						<% end %>
						<li class=""><%= link_to 'User Statistics', charts_path %></li>
						<li><%= link_to "Sign out", signout_path, :method => :delete %></li> 
					<% else %>
						 <li><%= link_to "Sign in", signin_path %></li> 
					<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'bootstrap-responsive', :media => 'all' %> 
<%= stylesheet_link_tag    "application", :media => "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sales Quiz and Leaderboard | <%= @title %></title>
  <%= render 'layouts/stylesheets' %>	
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container" style="padding-top:50px;">
	<section class="round">
		<% flash.each do |key, value| %> 
			<div class="alert flash <%= key %>">
				<a class="close">×</a>
				<%= value %>
			</div>
		<% end %>
	</section>
	<% if flash[:error] || flash[:errors] %>
	    <p id="flash_errors" class="messages errors"><%= flash[:error] || flash[:errors] %></p>
	    <%= javascript_tag "$('#flash_errors').effect('highlight',{},1000);" %>
	  <% end %>
	<%= image_tag 'http://www.janssen.com.ar/admin/logos/68invega.gif' %>
	<%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>